### PR TITLE
Invalid Array Length Bug Fix

### PR DESCRIPTION
**Pull request by markhayden**
Ran into an `Invalid array length` error when running jstag. The first data push happens but any subsequent pushes fail, resulting in no data layer collection. Looks to be caused by a random jQuery plugin modifying the Array.prototype.

Paired with @DingoEatingFuzz on this fix.

### CODE REVIEW

**Comment by araddon** [comment]
:+1:

**Comment by araddon** [comment]
can you rev the version please

**Comment by DingoEatingFuzz** [comment]
:+1:

**Comment by markhayden** [comment]
changed version to 1.26

**Comment by araddon** [comment]
lgtm

**Pull request merged**
